package Administrador;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.text.AbstractDocument.Content;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
     
    }
     void setColor(JPanel jpanelb){
    jpanelb.setBackground(new Color(181,218,240));
    }
    
    void resetColor(JPanel jpanelb){
    jpanelb.setBackground(new Color(255,255,255));
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jpanelb1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpanelb2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpanelb3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpanelb4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelinicio = new javax.swing.JPanel();
        paneli = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(0, 0, 255));

        jLabel5.setFont(new java.awt.Font("Manrope ExtraBold", 0, 36)); // NOI18N
        jLabel5.setText("LISTA DE PEDIDOS ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(71, 71, 71))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel5)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(23, 23, 23))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen_de_WhatsApp_2024-11-21_a_las_16.51.39_2c052284-removebg-preview.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelop.setBackground(new java.awt.Color(255, 255, 255));
        panelop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador");
        panelop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jLabel2.setBackground(new java.awt.Color(118, 120, 237));
        jLabel2.setForeground(new java.awt.Color(118, 120, 237));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis DC\\Downloads\\user_8763547.png")); // NOI18N
        panelop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");
        panelop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 20));
        panelop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, -1));

        jButton4.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow (1).png"))); // NOI18N
        jButton4.setText("Cerrar sesión");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelop.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 60));

        jpanelb1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb1MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/business_13641453.png"))); // NOI18N
        jLabel4.setText("Empleados");

        javax.swing.GroupLayout jpanelb1Layout = new javax.swing.GroupLayout(jpanelb1);
        jpanelb1.setLayout(jpanelb1Layout);
        jpanelb1Layout.setHorizontalGroup(
            jpanelb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpanelb1Layout.setVerticalGroup(
            jpanelb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelop.add(jpanelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 50));

        jpanelb2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb2MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/washing-machine_8081669.png"))); // NOI18N
        jLabel7.setText("Pedidos");

        javax.swing.GroupLayout jpanelb2Layout = new javax.swing.GroupLayout(jpanelb2);
        jpanelb2.setLayout(jpanelb2Layout);
        jpanelb2Layout.setHorizontalGroup(
            jpanelb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpanelb2Layout.setVerticalGroup(
            jpanelb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelop.add(jpanelb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 60));

        jpanelb3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb3.setForeground(new java.awt.Color(0, 0, 0));
        jpanelb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb3MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/list_654116 (1).png"))); // NOI18N
        jLabel9.setText("Servicios");

        javax.swing.GroupLayout jpanelb3Layout = new javax.swing.GroupLayout(jpanelb3);
        jpanelb3.setLayout(jpanelb3Layout);
        jpanelb3Layout.setHorizontalGroup(
            jpanelb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelb3Layout.setVerticalGroup(
            jpanelb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        panelop.add(jpanelb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 50));

        jpanelb4.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb4.setForeground(new java.awt.Color(0, 0, 0));
        jpanelb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb4MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/support.png"))); // NOI18N
        jLabel10.setText("Clientes");

        javax.swing.GroupLayout jpanelb4Layout = new javax.swing.GroupLayout(jpanelb4);
        jpanelb4.setLayout(jpanelb4Layout);
        jpanelb4Layout.setHorizontalGroup(
            jpanelb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelb4Layout.setVerticalGroup(
            jpanelb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelb4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelop.add(jpanelb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, 50));

        getContentPane().add(panelop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 480));

        panelinicio.setBackground(new java.awt.Color(118, 120, 237));

        paneli.setBackground(new java.awt.Color(181, 218, 240));
        paneli.setPreferredSize(new java.awt.Dimension(560, 480));
        paneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen_de_WhatsApp_2024-11-21_a_las_16.51.39_2c052284-removebg-preview.png"))); // NOI18N
        paneli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 444, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis DC\\Downloads\\pngwing.com (1).png")); // NOI18N
        paneli.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        javax.swing.GroupLayout panelinicioLayout = new javax.swing.GroupLayout(panelinicio);
        panelinicio.setLayout(panelinicioLayout);
        panelinicioLayout.setHorizontalGroup(
            panelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioLayout.createSequentialGroup()
                .addComponent(paneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelinicioLayout.setVerticalGroup(
            panelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioLayout.createSequentialGroup()
                .addComponent(paneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 560, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        IniciaSesion is=new IniciaSesion();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jpanelb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb1MouseClicked
        // TODO add your handling code here:
        panelop.setVisible(true);
        
        
         panelempleados p1 = new panelempleados();
    p1.setSize(560, 480); // Sugerir tamaño preferido
    p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

    panelinicio.removeAll();
    panelinicio.setLayout(new BorderLayout());
    panelinicio.add(p1, BorderLayout.CENTER);
    panelinicio.revalidate();
        
       
    }//GEN-LAST:event_jpanelb1MouseClicked

    private void jpanelb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb1MousePressed
        // TODO add your handling code here:
        
        setColor(jpanelb1);
        resetColor(jpanelb2);
        resetColor(jpanelb3);
        resetColor(jpanelb4);

       
    }//GEN-LAST:event_jpanelb1MousePressed

    private void jpanelb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb2MouseClicked
        // TODO add your handling code here:
           panelpedidosadmin p1 = new panelpedidosadmin();
    p1.setSize(560, 480); // Sugerir tamaño preferido
    p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

    panelinicio.removeAll();
    panelinicio.setLayout(new BorderLayout());
    panelinicio.add(p1, BorderLayout.CENTER);
    panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb2MouseClicked

    private void jpanelb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb2MousePressed
        // TODO add your handling code here:
        setColor(jpanelb2);

        resetColor(jpanelb1);
        resetColor(jpanelb3);
        resetColor(jpanelb4);

    }//GEN-LAST:event_jpanelb2MousePressed

    private void jpanelb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb3MouseClicked
        // TODO add your handling code here:
          panelop.setVisible(true);
          
       panelserviciosadmin p1 = new panelserviciosadmin();
    p1.setSize(560, 480); // Sugerir tamaño preferido
    p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

    panelinicio.removeAll();
    panelinicio.setLayout(new BorderLayout());
    panelinicio.add(p1, BorderLayout.CENTER);
    panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb3MouseClicked

    private void jpanelb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb3MousePressed
        // TODO add your handling code here:
        setColor(jpanelb3);
        resetColor(jpanelb1);
        resetColor(jpanelb2);
        resetColor(jpanelb4);

    }//GEN-LAST:event_jpanelb3MousePressed

    private void jpanelb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb4MouseClicked
        // TODO add your handling code here:
          panelop.setVisible(true);
     panelclientesadmin p1 = new panelclientesadmin();
    p1.setSize(560, 480); // Sugerir tamaño preferido
    p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

    panelinicio.removeAll();
    panelinicio.setLayout(new BorderLayout());
    panelinicio.add(p1, BorderLayout.CENTER);
    panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb4MouseClicked

    private void jpanelb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb4MousePressed
        // TODO add your handling code here:
        setColor(jpanelb4);
        resetColor(jpanelb1);
        resetColor(jpanelb2);
        resetColor(jpanelb3);

    }//GEN-LAST:event_jpanelb4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jpanelb1;
    private javax.swing.JPanel jpanelb2;
    private javax.swing.JPanel jpanelb3;
    private javax.swing.JPanel jpanelb4;
    private javax.swing.JPanel paneli;
    private javax.swing.JPanel panelinicio;
    private javax.swing.JPanel panelop;
    // End of variables declaration//GEN-END:variables
}
