package Administrador;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class IniciaSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciaSesion
     */
    public IniciaSesion() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabel78 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtusu1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtpass1 = new javax.swing.JPasswordField();
        chkMostrarPass = new javax.swing.JCheckBox();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 218, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel78.setForeground(new java.awt.Color(0, 0, 0));
        jlabel78.setText("_______________________________");
        jPanel1.add(jlabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 16, 16));

        jLabel8.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        txtusu1.setBackground(new java.awt.Color(181, 218, 240));
        txtusu1.setBorder(null);
        txtusu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusu1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 236, 150, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 16, 16));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("_______________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 417, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen_de_WhatsApp_2024-11-21_a_las_16.51.39_2c052284-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 370, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bub.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 440, 170));

        btnInicioSesion.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnInicioSesion.setText("iniciar sesion");
        btnInicioSesion.setBorder(null);
        btnInicioSesion.setContentAreaFilled(false);
        btnInicioSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInicioSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/userLabel.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jButton3.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("¿Nuevo usuario?");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, -1));
        jPanel1.add(txtpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, -1));

        chkMostrarPass.setText("ver cotraseña");
        chkMostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarPassActionPerformed(evt);
            }
        });
        jPanel1.add(chkMostrarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
     
        FrameMenu nv = new FrameMenu();
    String credencial = txtusu1.getText().trim();
    
    // Usar getPassword() y convertir a String
    char[] passwordChars = txtpass1.getPassword();
    String contraseña = new String(passwordChars);
    
    if (credencial.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Por favor ingrese sus credenciales completas", 
            "Campos vacíos", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = Conexion.getConnection()) {
        String sql = "SELECT Puesto, Nombre, IdUsuario FROM dbo.Usuario WHERE " +
                     "(CONVERT(VARCHAR, IdUsuario) = ? OR Nombre = ?) AND Contraseña = ?";
        
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, credencial);
        stmt.setString(2, credencial);
        stmt.setString(3, contraseña);

        var rs = stmt.executeQuery();

        if (rs.next()) {
            String puesto = rs.getString("Puesto");
            String nombreCompleto = rs.getString("Nombre");
            int idUsuario = rs.getInt("IdUsuario");
            
            // Solo agregamos esta línea para mostrar la info en FrameMenu
            nv.mostrarInfoUsuario(nombreCompleto, puesto);
            
            // El resto del código permanece igual
            JOptionPane.showMessageDialog(this, 
                "<html><b>Bienvenido/a:</b> " + nombreCompleto + "<br>" +
                "<b>ID Usuario:</b> " + idUsuario + "<br>" +
                "<b>Rol:</b> " + puesto + "</html>",
                "Inicio de sesión exitoso",
                JOptionPane.INFORMATION_MESSAGE);

            nv.setIdUsuarioActual(idUsuario);
            
            if ("Administrador".equalsIgnoreCase(puesto)) {
                nv.setVisible(true);
            } else if ("Empleado".equalsIgnoreCase(puesto)) {
                nv.deshabilitarBotonesParaEmpleado();
                nv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Rol de usuario no reconocido: " + puesto, 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Credenciales incorrectas. Intente nuevamente.", 
                "Error de autenticación", 
                JOptionPane.ERROR_MESSAGE);
        }
     } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error de conexión: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Limpieza segura del array de contraseña
        if (passwordChars != null) {
            java.util.Arrays.fill(passwordChars, '\0'); // Llenar con caracter nulo
        }
        txtpass1.setText(""); // Limpiar el campo visual
    }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void txtusu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusu1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Registrarse2 p=new Registrarse2();
        p.setVisible(true);
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chkMostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarPassActionPerformed
        // TODO add your handling code here:
          if (chkMostrarPass.isSelected()) {
        txtpass1.setEchoChar((char) 0); // Mostrar texto plano
    } else {
        txtpass1.setEchoChar('•'); // Ocultar con caracteres de contraseña
        // Alternativa: txtpass1.setEchoChar('\u2022'); para un punto más grande
    }
    }//GEN-LAST:event_chkMostrarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciaSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JCheckBox chkMostrarPass;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlabel78;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JTextField txtusu1;
    // End of variables declaration//GEN-END:variables
}
