package Administrador;

import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class panelempleados extends javax.swing.JPanel {

    /**
     * Creates new form panelempleados
     */
    
    public panelempleados() {
         try (Connection conn = Conexion.getConnection()) {
            System.out.println("Conexión exitosa:D.");
        } catch (SQLException e) {
            System.out.println("Error de conexión");
            e.printStackTrace();
            
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEmpleado = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        BarraDeBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        BarraDeBusqueda1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BarraDeBusqueda3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BarraDeBusqueda4 = new javax.swing.JTextField();
        BarraDeBusqueda5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BarraDeBusqueda6 = new javax.swing.JTextField();
        BarraDeBusqueda7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboBoxPuesto = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 218, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Puesto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, -1, -1));

        jtbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdUsuario", "Nombre", "Puesto", "NewAttr", "Turno", "Registro"
            }
        ));
        jScrollPane1.setViewportView(jtbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 350, 370));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Empleado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        BarraDeBusqueda.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda.setBorder(null);
        jPanel1.add(BarraDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, 20));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("___________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Borrar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 430, 130, 34));

        jButton5.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setVerifyInputWhenFocusTarget(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 50, -1));

        jButton6.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jButton6.setText("Editar");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setVerifyInputWhenFocusTarget(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 382, 130, 30));

        jButton7.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar (1).png"))); // NOI18N
        jButton7.setText("Añadir");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 340, 128, -1));

        BarraDeBusqueda1.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda1.setBorder(null);
        jPanel1.add(BarraDeBusqueda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 250, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("________________________");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        BarraDeBusqueda3.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda3.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda3.setBorder(null);
        jPanel1.add(BarraDeBusqueda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 250, 20));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        BarraDeBusqueda4.setBackground(new java.awt.Color(118, 120, 237));
        BarraDeBusqueda4.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda4.setBorder(null);
        jPanel1.add(BarraDeBusqueda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 250, 20));

        BarraDeBusqueda5.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda5.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda5.setBorder(null);
        jPanel1.add(BarraDeBusqueda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 130, 20));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("________________________");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        BarraDeBusqueda6.setBackground(new java.awt.Color(102, 204, 255));
        BarraDeBusqueda6.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda6.setBorder(null);
        jPanel1.add(BarraDeBusqueda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 130, 20));

        BarraDeBusqueda7.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda7.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeBusqueda7.setBorder(null);
        jPanel1.add(BarraDeBusqueda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 250, 20));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Horario:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        comboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        comboBoxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPuestoActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 122, 120, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                                          
    // Obtener la fila seleccionada en la tabla
    int filaSeleccionada = jtbEmpleado.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Obtener el ID del empleado seleccionado (primera columna en la tabla)
    int idUsuario = (int) jtbEmpleado.getValueAt(filaSeleccionada, 0);
    
    // Confirmar la eliminación
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro que desea eliminar este empleado?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        try (Connection conn = Conexion.getConnection()) {
            String deleteSql = "DELETE FROM dbo.Usuario WHERE IdUsuario = ?";
            PreparedStatement stmt = conn.prepareStatement(deleteSql);
            stmt.setInt(1, idUsuario);
            
            int filasAfectadas = stmt.executeUpdate();
            
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Actualizar la tabla después de eliminar
                DefaultTableModel model = (DefaultTableModel) jtbEmpleado.getModel();
                model.removeRow(filaSeleccionada);
                
                // Opcional: Recargar todos los datos de la tabla
                
                model.setRowCount(0);
                String selectSql = "SELECT * FROM dbo.Usuario";
                try (PreparedStatement selectStmt = conn.prepareStatement(selectSql); 
                     var rs = selectStmt.executeQuery()) {
                    while (rs.next()) {
                        Object[] row = {
                            rs.getInt("IdUsuario"), 
                            rs.getString("Nombre"),
                            rs.getString("Puesto"),
                            rs.getString("Telefono"),
                            rs.getString("Turno"),
                            rs.getString("RegistroAsistencia")
                        };
                        model.addRow(row);
                    }
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el empleado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnEliminarActionPerformed
    private void refrescarTabla() {
    DefaultTableModel model = (DefaultTableModel) jtbEmpleado.getModel();
    model.setRowCount(0);
    
    try (Connection conn = Conexion.getConnection()) {
        String selectSql = "SELECT * FROM dbo.Usuario";
        try (PreparedStatement stmt = conn.prepareStatement(selectSql); 
             var rs = stmt.executeQuery()) {
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("IdUsuario"), 
                    rs.getString("Nombre"),
                    rs.getString("Puesto"),
                    rs.getString("Telefono"),
                    rs.getString("Turno"),
                };
                model.addRow(row);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        refrescarTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try (Connection conn = Conexion.getConnection()) {
    String insertSql = "INSERT INTO dbo.Usuario (Nombre, Puesto, Telefono, Turno, RegistroAsistencia,Contraseña) VALUES (?, ?, ?, ?, ?,?)";
    PreparedStatement stmt = conn.prepareStatement(insertSql);
    
    String nombre = BarraDeBusqueda1.getText();
     String puesto = (String) comboBoxPuesto.getSelectedItem();
    String telefono = BarraDeBusqueda3.getText();
    String turno = BarraDeBusqueda5.getText();
    String registro = BarraDeBusqueda6.getText();
    
    String Contraseña = JOptionPane.showInputDialog("Ingresar contraseña");
    
    stmt.setString(1, nombre);
    stmt.setString(2, puesto);
    stmt.setString(3, telefono);
    stmt.setString(4, turno);
    stmt.setString(5, registro);
    stmt.setString(6, Contraseña);
    
    int filasAfectadas = stmt.executeUpdate();
    
    if (filasAfectadas > 0) {
        System.out.println("Empleado insertado correctamente.");
        
        // Actualizar JTable
        DefaultTableModel model = (DefaultTableModel) jtbEmpleado.getModel();
        model.setRowCount(0); // Limpiar tabla antes de actualizar
        
        String selectSql = "SELECT * FROM dbo.Usuario";
        try (PreparedStatement selectStmt = conn.prepareStatement(selectSql); var rs = selectStmt.executeQuery()) {
           while (rs.next()) {
                Object[] row = {
                rs.getInt("IdUsuario"), 
                rs.getString("Nombre"),
                rs.getString("Puesto"),
                rs.getString("Telefono"),
                rs.getString("Turno"),
                rs.getString("RegistroAsistencia")
                    };
        model.addRow(row);
    }

        }
    } else {
        System.out.println("Error al insertar el empleado.");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton7ActionPerformed

    private void comboBoxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPuestoActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusqueda;
    private javax.swing.JTextField BarraDeBusqueda1;
    private javax.swing.JTextField BarraDeBusqueda3;
    private javax.swing.JTextField BarraDeBusqueda4;
    private javax.swing.JTextField BarraDeBusqueda5;
    private javax.swing.JTextField BarraDeBusqueda6;
    private javax.swing.JTextField BarraDeBusqueda7;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> comboBoxPuesto;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbEmpleado;
    // End of variables declaration//GEN-END:variables
}
