package Administrador;

import java.io.StringReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class panelclientesadmin extends javax.swing.JPanel {

    /**
     * Creates new form panelclientesadmin
     */
    public panelclientesadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblClientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextCliente1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextCliente2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextCliente3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextCliente4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("_________________________");

        jTextField8.setBackground(new java.awt.Color(118, 120, 237));
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 218, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblClientes.setBackground(new java.awt.Color(51, 51, 51));
        jtblClientes.setForeground(new java.awt.Color(255, 255, 255));
        jtblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCliente", "Nombre", "Domicilio", "Telefono", "Correo", "FechaRegistro"
            }
        ));
        jtblClientes.setGridColor(new java.awt.Color(51, 51, 51));
        jtblClientes.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jtblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 340, 380));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 79, 41));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 101, 41));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Domicilio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 101, 41));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 101, 41));

        jLabel11.setBackground(new java.awt.Color(118, 120, 237));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jTextCliente1.setBackground(new java.awt.Color(181, 218, 240));
        jTextCliente1.setBorder(null);
        jTextCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 30));

        jTextField6.setBackground(new java.awt.Color(181, 218, 240));
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 350, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("_________________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 350, -1));

        jButton7.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("_________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, -1));

        jTextCliente2.setBackground(new java.awt.Color(181, 218, 240));
        jTextCliente2.setBorder(null);
        jTextCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCliente2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 39));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("_________________________");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 180, -1));

        jTextCliente3.setBackground(new java.awt.Color(181, 218, 240));
        jTextCliente3.setBorder(null);
        jTextCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCliente3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 39));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("_________________________");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 180, -1));

        jTextCliente4.setBackground(new java.awt.Color(181, 218, 240));
        jTextCliente4.setBorder(null);
        jTextCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCliente4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 180, 39));

        jButton8.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar (2).png"))); // NOI18N
        jButton8.setText("Eliminar");
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.setVerifyInputWhenFocusTarget(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 30));

        jButton9.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        jButton9.setText("Editar");
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setVerifyInputWhenFocusTarget(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 140, -1));

        btnAgregarCliente.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N
        btnAgregarCliente.setText("Añadir");
        btnAgregarCliente.setBorder(null);
        btnAgregarCliente.setContentAreaFilled(false);
        btnAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregarCliente.setVerifyInputWhenFocusTarget(false);
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 120, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCliente1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCliente2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCliente3ActionPerformed

    private void jTextCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCliente4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        
        try (Connection conn = Conexion.getConnection()) {
    String insertSql = "INSERT INTO dbo.Cliente (Nombre, Direccion, Telefono, CorreoElectronico, FechaRegistro) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement stmt = conn.prepareStatement(insertSql);
    
    String nombre = jTextCliente1.getText();
     String direccion =jTextCliente2.getText();
    String telefono = jTextCliente3.getText();
    String correo = jTextCliente4.getText();
    //Metodo para obtener contraseña actual
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String ftFecha= fechaActual.format(formatter);

    stmt.setString(1, nombre);
    stmt.setString(2, direccion);
    stmt.setString(3, telefono);
    stmt.setString(4, correo);
    stmt.setString(5, ftFecha);

    int filasAfectadas = stmt.executeUpdate();
    
    if (filasAfectadas > 0) {
        System.out.println("Cliente insertado correctamente.");
        
        // Actualizar JTable
        DefaultTableModel model = (DefaultTableModel) jtblClientes.getModel();
        model.setRowCount(0); // Limpiar tabla antes de actualizar
        
        String selectSql = "SELECT * FROM dbo.Cliente";
        try (PreparedStatement selectStmt = conn.prepareStatement(selectSql); var rs = selectStmt.executeQuery()) {
           while (rs.next()) {
                Object[] row = {
                rs.getInt("IdCliente"), 
                rs.getString("Nombre"),
                rs.getString("Direccion"),
                rs.getString("Telefono"),
                rs.getString("CorreoElectronico"),
                rs.getString("FechaRegistro")
                    };
        model.addRow(row);
    }

        }
    } else {
        System.out.println("Error al insertar el empleado.");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_btnAgregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCliente1;
    private javax.swing.JTextField jTextCliente2;
    private javax.swing.JTextField jTextCliente3;
    private javax.swing.JTextField jTextCliente4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable jtblClientes;
    // End of variables declaration//GEN-END:variables
}
