package Administrador;
import java.io.StringReader;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class panelserviciosadmin extends javax.swing.JPanel {
private int idServicioSeleccionado = -1;
    /**
     * Creates new form panelserviciosadmin
     */
    public panelserviciosadmin() {
        initComponents();
        actualizarTablaServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BarraDeBusqueda = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelNomSer = new javax.swing.JLabel();
        LabelCostSer = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        TxtCost = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 218, 240));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Servicio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 40));

        BarraDeBusqueda.setBackground(new java.awt.Color(181, 218, 240));
        BarraDeBusqueda.setBorder(null);
        jPanel1.add(BarraDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        jtblServicios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID Servicio", "Nombre", "Descripcion", "Costo P/kg"
            }
        ));
        jtblServicios.setToolTipText("");
        jtblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblServiciosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtblServicios);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 530, 400));

        jLabel1.setText("_______________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 190, -1));

        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscar.setVerifyInputWhenFocusTarget(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, 30));

        btnInsertar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInsertar.setBorder(null);
        btnInsertar.setContentAreaFilled(false);
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInsertar.setVerifyInputWhenFocusTarget(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, 40));

        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar (2).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 60));

        btnActualizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        btnActualizar.setText("Editar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 110, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Servicio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 79, 41));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Costo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 41));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 101, 41));

        LabelNomSer.setBackground(new java.awt.Color(118, 120, 237));
        LabelNomSer.setText("_____________________________");
        jPanel1.add(LabelNomSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, -1));

        LabelCostSer.setText("___________");
        jPanel1.add(LabelCostSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, -1));

        txtNombre.setBackground(new java.awt.Color(181, 218, 240));
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 39));

        TxtCost.setBackground(new java.awt.Color(181, 218, 240));
        TxtCost.setBorder(null);
        TxtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCostActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 30));

        btnGuardar.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N
        btnGuardar.setText("Agregar");
        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardar.setVerifyInputWhenFocusTarget(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 30));

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel5.setText("Busqueda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        TxtDesc.setColumns(20);
        TxtDesc.setRows(5);
        jScrollPane1.setViewportView(TxtDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 220, 110));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("$");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String textoBusqueda = BarraDeBusqueda.getText().trim();
    DefaultTableModel model = (DefaultTableModel) jtblServicios.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de la búsqueda

    if (textoBusqueda.isEmpty()) {
        actualizarTablaServicios();
        return;
    }

    try {
        // Determinar si es búsqueda por ID o por nombre
        if (textoBusqueda.matches("\\d+")) {
            // Búsqueda por ID
            buscarPorId(model, Integer.parseInt(textoBusqueda));
        } else {
            // Búsqueda por nombre
            buscarPorNombre(model, textoBusqueda);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID válido (número)", 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Método auxiliar para búsqueda por ID
private void buscarPorId(DefaultTableModel model, int idServicio) {
    String sql = "SELECT [IdServicio], [TipoServicio], [Descripcion], [PrecioUnitario] " +
                 "FROM [Servicio] WHERE [IdServicio] = ?";
    
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setInt(1, idServicio);
        
        try (ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("IdServicio"),
                    rs.getString("TipoServicio"),
                    rs.getString("Descripcion"),
                    rs.getFloat("PrecioUnitario")
                });
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se encontró servicio con ID: " + idServicio, 
                    "Información", JOptionPane.INFORMATION_MESSAGE);
                actualizarTablaServicios();
            }
        }
    } catch (SQLException ex) {
        mostrarErrorSQL(ex);
    }
}

// Método auxiliar para búsqueda por nombre
private void buscarPorNombre(DefaultTableModel model, String nombre) {
    String sql = "SELECT [IdServicio], [TipoServicio], [Descripcion], [PrecioUnitario] " +
                 "FROM [Servicio] WHERE [TipoServicio] LIKE ?";
    
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, "%" + nombre + "%");
        
        try (ResultSet rs = pstmt.executeQuery()) {
            boolean encontrado = false;
            while (rs.next()) {
                encontrado = true;
                model.addRow(new Object[]{
                    rs.getInt("IdServicio"),
                    rs.getString("TipoServicio"),
                    rs.getString("Descripcion"),
                    rs.getFloat("PrecioUnitario")
                });
            }
            
            if (!encontrado) {
                mostrarSugerencias(nombre);
                actualizarTablaServicios();
            }
        }
    } catch (SQLException ex) {
        mostrarErrorSQL(ex);
    }
}

// Método para mostrar sugerencias
private void mostrarSugerencias(String textoBusqueda) {
    List<String> sugerencias = new ArrayList<>();
    String sql = "SELECT DISTINCT [TipoServicio] FROM [Servicio] WHERE [TipoServicio] LIKE ?";
    
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, "%" + textoBusqueda + "%");
        
        try (ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                sugerencias.add(rs.getString("TipoServicio"));
            }
        }
        
        if (!sugerencias.isEmpty()) {
            String mensaje = "No se encontraron servicios exactos.\n\n" +
                           "¿Quizás quisiste buscar alguno de estos?\n" +
                           String.join("\n", sugerencias.subList(0, Math.min(sugerencias.size(), 5)));
            JOptionPane.showMessageDialog(this, mensaje, 
                "Sugerencias", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se encontraron servicios con: " + textoBusqueda, 
                "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException ex) {
        mostrarErrorSQL(ex);
    }
}

// Método para manejar errores SQL
private void mostrarErrorSQL(SQLException ex) {
    JOptionPane.showMessageDialog(this, 
        "Error de base de datos: " + ex.getMessage(), 
        "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void TxtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCostActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    String nombre = txtNombre.getText().trim();       // Corresponde a TipoServicio
    String descripcion = TxtDesc.getText().trim();    // Corresponde a Descripcion
    
    try {
        float costo = Float.parseFloat(TxtCost.getText().trim());  // Corresponde a PrecioUnitario
        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El tipo de servicio es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = Conexion.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(
                 "INSERT INTO dbo.Servicio (TipoServicio, Descripcion, PrecioUnitario) VALUES (?, ?, ?)")) {
            
            pstmt.setString(1, nombre);
            pstmt.setString(2, descripcion);
            pstmt.setFloat(3, costo);
            
            if (pstmt.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Servicio registrado en dbo.Servicio");
                limpiarCampos();
            }
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Precio debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error en BD: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    limpiarCampos();
        actualizarTablaServicios();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. Obtener valores
    String nombre = txtNombre.getText().trim();
    String descripcion = TxtDesc.getText().trim();
    
    try {
        float costo = Float.parseFloat(TxtCost.getText().trim());
        
        // 2. Validación básica
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del servicio es obligatorio", 
                                       "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return;
        }
        
        // 3. Determinar si es INSERT o UPDATE
        try (Connection conn = Conexion.getConnection()) {
            String sql;
            boolean esActualizacion = (idServicioSeleccionado > 0);
            
            if (esActualizacion) {
                sql = "UPDATE dbo.Servicio SET TipoServicio=?, Descripcion=?, PrecioUnitario=? WHERE IdServicio=?";
            } else {
                sql = "INSERT INTO dbo.Servicio (TipoServicio, Descripcion, PrecioUnitario) VALUES (?, ?, ?)";
            }
            
            // 4. Ejecutar operación
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, nombre);
                pstmt.setString(2, descripcion);
                pstmt.setFloat(3, costo);
                
                if (esActualizacion) {
                    pstmt.setInt(4, idServicioSeleccionado);
                }
                
                int filasAfectadas = pstmt.executeUpdate();
                
                // 5. Manejar resultados
                if (filasAfectadas > 0) {
                    String mensaje = esActualizacion ? "Servicio actualizado" : "Servicio registrado";
                    JOptionPane.showMessageDialog(this, mensaje);
                    
                    // 6. Resetear interfaz EXACTAMENTE como lo pides
                    limpiarCampos();
                    btnGuardar.setText("Guardar"); // Equivalente a tu "Añadir"
                    idServicioSeleccionado = -1;    // Equivalente a tu clienteSeleccionadoId = -1
                    
                    // 7. Actualizar tabla
                    actualizarTablaServicios();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en base de datos: " + ex.getMessage(), 
                                       "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El costo debe ser un número válido", 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        TxtCost.requestFocus();
    }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       if (idServicioSeleccionado <= 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un servicio de la tabla primero", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String nombre = txtNombre.getText().trim();
    String descripcion = TxtDesc.getText().trim();
    
    try {
        float costo = Float.parseFloat(TxtCost.getText().trim());

        try (Connection conn = Conexion.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(
                 "UPDATE dbo.Servicio SET TipoServicio=?, Descripcion=?, PrecioUnitario=? WHERE IdServicio=?")) {
            
            pstmt.setString(1, nombre);
            pstmt.setString(2, descripcion);
            pstmt.setFloat(3, costo);
            pstmt.setInt(4, idServicioSeleccionado);
            
            if (pstmt.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Servicio actualizado correctamente");
                actualizarTablaServicios(); // Actualizar la tabla
                limpiarCampos();
                idServicioSeleccionado = -1; // Resetear selección
            }
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Formato de precio inválido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    limpiarCampos();
    actualizarTablaServicios();
    
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (idServicioSeleccionado <= 0) {
    JOptionPane.showMessageDialog(this, "Seleccione un servicio de la tabla primero", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Primero verificamos si el servicio está siendo usado en otras tablas
try (Connection conn = Conexion.getConnection()) {
    // Consulta para verificar si el servicio está siendo usado en otras tablas
    String sqlVerificarUso = "SELECT COUNT(*) AS total FROM dbo.Pedido WHERE IdServicio = ?";
    
    try (PreparedStatement pstmtVerificar = conn.prepareStatement(sqlVerificarUso)) {
        pstmtVerificar.setInt(1, idServicioSeleccionado);
        
        try (ResultSet rs = pstmtVerificar.executeQuery()) {
            if (rs.next() && rs.getInt("total") > 0) {
                JOptionPane.showMessageDialog(this, 
                    "No se puede eliminar el servicio porque está siendo utilizado en otra tabla", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }
    
    // Si pasa la validación, pedir confirmación
    int confirmacion = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de eliminar este servicio permanentemente?", 
        "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        try (PreparedStatement pstmtEliminar = conn.prepareStatement(
            "DELETE FROM dbo.Servicio WHERE IdServicio=?")) {
            
            pstmtEliminar.setInt(1, idServicioSeleccionado);
            
            if (pstmtEliminar.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Servicio eliminado exitosamente");
                actualizarTablaServicios();
                limpiarCampos();
                idServicioSeleccionado = -1;
             }
          }
       }
     } catch (SQLException ex) {
       JOptionPane.showMessageDialog(this, 
         "Error en la operación: " + ex.getMessage(), 
         "Error", JOptionPane.ERROR_MESSAGE);
       ex.printStackTrace();
    }

     limpiarCampos();
     actualizarTablaServicios();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtblServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblServiciosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblServiciosMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
actualizarTablaServicios();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void actualizarTablaServicios() {
    DefaultTableModel model = (DefaultTableModel) jtblServicios.getModel();
    model.setRowCount(0); // Limpiar tabla
    
    String sql = "SELECT IdServicio, TipoServicio, Descripcion, PrecioUnitario FROM dbo.Servicio";
    
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {
        
        // Llenar tabla
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("IdServicio"),
                rs.getString("TipoServicio"),
                rs.getString("Descripcion"),
                String.format("$%.2f", rs.getFloat("PrecioUnitario")) // Formato monetario
            });
        }
        
        // Configurar listener para selección
        jtblServicios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = jtblServicios.getSelectedRow();
                if (fila >= 0) {
                    idServicioSeleccionado = (int) jtblServicios.getValueAt(fila, 0);
                    cargarServicioParaEdicion(idServicioSeleccionado);
                }
            }
        });
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al actualizar tabla:\n" + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void cargarServicioParaEdicion(int idServicio) {
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(
             "SELECT TipoServicio, Descripcion, PrecioUnitario FROM dbo.Servicio WHERE IdServicio=?")) {
        
        pstmt.setInt(1, idServicio);
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            txtNombre.setText(rs.getString("TipoServicio"));
            TxtDesc.setText(rs.getString("Descripcion"));
            TxtCost.setText(String.valueOf(rs.getFloat("PrecioUnitario")));
            btnGuardar.setText("Actualizar");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al cargar servicio: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void cargarServicio(int idServicio) {
    try (Connection conn = Conexion.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(
             "SELECT TipoServicio, Descripcion, PrecioUnitario FROM dbo.Servicio WHERE IdServicio=?")) {
        
        pstmt.setInt(1, idServicio);
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            txtNombre.setText(rs.getString("TipoServicio"));
            TxtDesc.setText(rs.getString("Descripcion"));
            TxtCost.setText(String.valueOf(rs.getFloat("PrecioUnitario")));
            idServicioSeleccionado = idServicio;
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar servicio", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    // Limpiar formulario
private void limpiarCampos() {
    txtNombre.setText("");
    TxtDesc.setText("");
    TxtCost.setText("");
    txtNombre.requestFocus();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusqueda;
    private javax.swing.JLabel LabelCostSer;
    private javax.swing.JLabel LabelNomSer;
    private javax.swing.JTextField TxtCost;
    private javax.swing.JTextArea TxtDesc;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtblServicios;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
