/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Luis DC
 */
public class Restablecer extends javax.swing.JFrame {

    /**
     * Creates new form Restablecer
     */
    public Restablecer() {
        initComponents();
        validarYEnviarCorreo();
    }
    private String codigoVerificacion;
    private int intentosRestantes = 3;
    private String empleadoId;
    private String correoEmpleado;

    // Método para enviar código de verificación
    private boolean enviarCodigoVerificacion() {
        // Generar código de 6 dígitos
        codigoVerificacion = String.format("%06d", new Random().nextInt(999999));
        
        // Configurar el enviador de correos
        EnviadorCorreos enviador = new EnviadorCorreos("serviciolavasoft@gmail.com", "tu_contraseña_de_aplicacion");
        
        String asunto = "Código de Verificación - Restablecer Contraseña";
        String cuerpo = "Estimado empleado,\n\n"
                      + "Su código de verificación para restablecer la contraseña es: " + codigoVerificacion + "\n\n"
                      + "Tiene 3 intentos para ingresarlo correctamente.\n\n"
                      + "Atentamente,\nEquipo de Lavasoft";
        
        return enviador.enviarCorreo(correoEmpleado, asunto, cuerpo);
    }                                       

    private void verificarCodigo() {
        while (intentosRestantes > 0) {
            String input = JOptionPane.showInputDialog(
                this, 
                "Ingrese el código enviado a su correo:\n"
                + "Intentos restantes: " + intentosRestantes,
                "Verificación de Código",
                JOptionPane.PLAIN_MESSAGE
            );

            if (input == null) { // Si el usuario cancela
                break;
            }

            if (input.equals(codigoVerificacion)) {
                cambiarContrasena();
                return;
            } else {
                intentosRestantes--;
                JOptionPane.showMessageDialog(this, 
                    "Código incorrecto. Intentos restantes: " + intentosRestantes);
            }
        }

        if (intentosRestantes == 0) {
            JOptionPane.showMessageDialog(this, 
                "Límite de intentos alcanzado. Por favor inicie el proceso nuevamente.");
        }
    }

    private void cambiarContrasena() {
        String nuevaContra = JOptionPane.showInputDialog(
            this,
            "Ingrese su nueva contraseña:",
            "Cambio de Contraseña",
            JOptionPane.PLAIN_MESSAGE
        );

        if (nuevaContra != null && !nuevaContra.isEmpty()) {
            try (Connection con = Conexion.getConnection()) {
                String update = "UPDATE empleados SET contrasena = ? WHERE id_empleado = ?";
                PreparedStatement ps = con.prepareStatement(update);
                ps.setString(1, nuevaContra);
                ps.setString(2, empleadoId);
                
                int filasActualizadas = ps.executeUpdate();
                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Contraseña actualizada exitosamente!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Error al actualizar la contraseña: " + ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcorr = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¡Has olvidado tu contraseña!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingresa tu telefono/correo asociado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, -1));

        txtIdEmpleado.setBackground(new java.awt.Color(153, 204, 255));
        txtIdEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEmpleado.setBorder(null);
        txtIdEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyPressed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingresa tu id empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txtcorr.setBackground(new java.awt.Color(153, 204, 255));
        txtcorr.setForeground(new java.awt.Color(0, 0, 0));
        txtcorr.setBorder(null);
        txtcorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorrKeyPressed(evt);
            }
        });
        jPanel1.add(txtcorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 271, 210, 20));

        btnVerificar.setBackground(new java.awt.Color(153, 204, 255));
        btnVerificar.setForeground(new java.awt.Color(0, 0, 0));
        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-correcta.png"))); // NOI18N
        btnVerificar.setText("Continuar");
        btnVerificar.setBorder(null);
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, 40));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 140, 40));

        lblid.setForeground(new java.awt.Color(0, 0, 0));
        lblid.setText("______________________________");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 220, 20));

        lbltel.setForeground(new java.awt.Color(0, 0, 0));
        lbltel.setText("______________________________");
        lbltel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbltelKeyPressed(evt);
            }
        });
        jPanel1.add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 220, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9710382.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarYEnviarCorreo() {
        
    }
   
    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
       String idEmpleado = txtIdEmpleado.getText().trim();
        
        if (idEmpleado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de empleado");
            return;
        }

        try (Connection con = Conexion.getConnection()) {
            // Buscar empleado en la base de datos
            String sql = "SELECT correo FROM empleados WHERE id_empleado = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, idEmpleado);
            var rs = stmt.executeQuery();

            if (rs.next()) {
                empleadoId = idEmpleado;
                correoEmpleado = rs.getString("correo");
                
                if (correoEmpleado != null && !correoEmpleado.isEmpty()) {
                    if (enviarCodigoVerificacion()) {
                        verificarCodigo();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al enviar el código");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El empleado no tiene correo registrado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Empleado no encontrado");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de conexión con la base de datos");
        }
     
       
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         IniciaSesion nv = new IniciaSesion();
        this.dispose();
        nv.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIdEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyPressed
        // TODO add your handling code here:
       
        lblid.setForeground(Color.black);
        
    }//GEN-LAST:event_txtIdEmpleadoKeyPressed

    private void lbltelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltelKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbltelKeyPressed

    private void txtcorrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorrKeyPressed
        // TODO add your handling code here:
        lbltel.setForeground(Color.black);
    }//GEN-LAST:event_txtcorrKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restablecer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtcorr;
    // End of variables declaration//GEN-END:variables

    
}
