/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

import com.sun.jdi.connect.Transport;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.net.PasswordAuthentication;
import java.sql.PreparedStatement;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis DC
 */
public class Restablecer extends javax.swing.JFrame {

    /**
     * Creates new form Restablecer
     */
    public Restablecer() {
        initComponents();
        validarYEnviarCorreo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcorr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¡Has olvidado tu contraseña!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/olvido.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingresa tu telefono asociado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 237, 235, -1));

        txtid.setBackground(new java.awt.Color(153, 204, 255));
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setBorder(null);
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingresa tu id empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 167, -1, -1));

        txtcorr.setBackground(new java.awt.Color(153, 204, 255));
        txtcorr.setForeground(new java.awt.Color(0, 0, 0));
        txtcorr.setBorder(null);
        txtcorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorrKeyPressed(evt);
            }
        });
        jPanel1.add(txtcorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 271, 210, 20));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-correcta.png"))); // NOI18N
        jButton1.setText("Continuar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 120, 40));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 332, 140, 40));

        lblid.setForeground(new java.awt.Color(0, 0, 0));
        lblid.setText("______________________________");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 220, 20));

        lbltel.setForeground(new java.awt.Color(0, 0, 0));
        lbltel.setText("______________________________");
        lbltel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbltelKeyPressed(evt);
            }
        });
        jPanel1.add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarYEnviarCorreo() {
        
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String id = txtid.getText().trim();
    String telefono = txtcorr.getText().trim();

    if (id.isEmpty() || telefono.isEmpty()) {
     lblid.setForeground(Color.red);
           lbltel.setForeground(Color.red);
    }
    
    if (id.isEmpty() || telefono.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
         lblid.setForeground(Color.red);
           lbltel.setForeground(Color.red);
           txtid.requestFocus();
           txtcorr.requestFocus();
        return;
    }

    try (java.sql.Connection con = Conexion.getConnection()) {
        String sql = "SELECT * FROM usuario WHERE idusuario = ? AND telefono = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, id);
        stmt.setString(2, telefono);
        java.sql.ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            // El usuario existe, solicitamos la nueva contraseña
            String nuevaContrasena = JOptionPane.showInputDialog(this, "Ingresa la nueva contraseña:");

            if (nuevaContrasena != null && !nuevaContrasena.trim().isEmpty()) {
                String updateSQL = "UPDATE usuario SET contraseña = ? WHERE idusuario = ?";
                PreparedStatement updateStmt = con.prepareStatement(updateSQL);
                updateStmt.setString(1, nuevaContrasena);
                updateStmt.setString(2, id);
                int filasActualizadas = updateStmt.executeUpdate();

                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Contraseña actualizada exitosamente.");
                    txtid.setText("");
                    txtcorr.setText("");
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar la contraseña.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ingresó una contraseña válida.");
                
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un usuario con ese ID y telefono.");
            lblid.setForeground(Color.red);
           lbltel.setForeground(Color.red);
           txtid.requestFocus();
           txtcorr.requestFocus();
           
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
    }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         IniciaSesion nv = new IniciaSesion();
        this.dispose();
        nv.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
       
        lblid.setForeground(Color.black);
        
    }//GEN-LAST:event_txtidKeyPressed

    private void lbltelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltelKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbltelKeyPressed

    private void txtcorrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorrKeyPressed
        // TODO add your handling code here:
        lbltel.setForeground(Color.black);
    }//GEN-LAST:event_txtcorrKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restablecer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restablecer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTextField txtcorr;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    
}
