package Empleado;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis DC
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jpanelb2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpanelb3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpanelb4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelinicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelop.setBackground(new java.awt.Color(255, 255, 255));
        panelop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleado");
        panelop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 20));

        jLabel2.setBackground(new java.awt.Color(118, 120, 237));
        jLabel2.setForeground(new java.awt.Color(118, 120, 237));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis DC\\Downloads\\user_8763547.png")); // NOI18N
        panelop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");
        panelop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 20));

        jButton4.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow (1).png"))); // NOI18N
        jButton4.setText("Cerrar sesión");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelop.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 60));

        jpanelb2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb2MousePressed(evt);
            }
        });
        jpanelb2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/washing-machine_8081669.png"))); // NOI18N
        jLabel7.setText("Pedidos");
        jpanelb2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 10, 120, 48));

        panelop.add(jpanelb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 60));

        jpanelb3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb3.setForeground(new java.awt.Color(0, 0, 0));
        jpanelb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb3MousePressed(evt);
            }
        });
        jpanelb3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_654116 (1).png"))); // NOI18N
        jLabel9.setText("Servicios");
        jpanelb3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, 140, 44));

        panelop.add(jpanelb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 50));

        jpanelb4.setBackground(new java.awt.Color(255, 255, 255));
        jpanelb4.setForeground(new java.awt.Color(0, 0, 0));
        jpanelb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelb4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelb4MousePressed(evt);
            }
        });
        jpanelb4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/support.png"))); // NOI18N
        jLabel10.setText("Clientes");
        jpanelb4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        panelop.add(jpanelb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 170, 40));

        jPanel1.add(panelop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelinicio.setBackground(new java.awt.Color(181, 218, 240));
        panelinicio.setPreferredSize(new java.awt.Dimension(560, 480));
        panelinicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagen_de_WhatsApp_2024-11-21_a_las_16.51.39_2c052284-removebg-preview.png"))); // NOI18N
        panelinicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngwing.com (1).png"))); // NOI18N
        panelinicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 130, -1));

        jPanel1.add(panelinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      void setColor(JPanel jpanelb){
    jpanelb.setBackground(new Color(181,218,240));
    }
    
    void resetColor(JPanel jpanelb){
    jpanelb.setBackground(new Color(255,255,255));
    } 
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        IniciaSesion nv=new IniciaSesion();
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jpanelb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb2MouseClicked
        // TODO add your handling code here:
        panelop.setVisible(true);
        
         panelpedidos p1 = new panelpedidos();
        p1.setSize(560, 480); // Sugerir tamaño preferido
        p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

        panelinicio.removeAll();
        panelinicio.setLayout(new BorderLayout());
        panelinicio.add(p1, BorderLayout.CENTER);
        panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb2MouseClicked

    private void jpanelb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb2MousePressed
        // TODO add your handling code here:
        setColor(jpanelb2);

        resetColor(jpanelb3);
        resetColor(jpanelb4);
    }//GEN-LAST:event_jpanelb2MousePressed

    private void jpanelb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb3MouseClicked
        // TODO add your handling code here:
        panelop.setVisible(true);

        panelservicioempleado p1 = new panelservicioempleado();
        p1.setSize(560, 480); // Sugerir tamaño preferido
        p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

        panelinicio.removeAll();
        panelinicio.setLayout(new BorderLayout());
        panelinicio.add(p1, BorderLayout.CENTER);
        panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb3MouseClicked

    private void jpanelb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb3MousePressed
        // TODO add your handling code here:
        setColor(jpanelb3);

        resetColor(jpanelb2);
        resetColor(jpanelb4);
    }//GEN-LAST:event_jpanelb3MousePressed

    private void jpanelb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb4MouseClicked
        // TODO add your handling code here:
        panelop.setVisible(true);
          panelclientesempleado p1 = new panelclientesempleado();
        p1.setSize(560, 480); // Sugerir tamaño preferido
        p1.setLocation(0, 0); // Configurar posición (opcional si usas un layout)

        panelinicio.removeAll();
        panelinicio.setLayout(new BorderLayout());
        panelinicio.add(p1, BorderLayout.CENTER);
        panelinicio.revalidate();
    }//GEN-LAST:event_jpanelb4MouseClicked

    private void jpanelb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelb4MousePressed
        // TODO add your handling code here:
        setColor(jpanelb4);

        resetColor(jpanelb2);
        resetColor(jpanelb3);
    }//GEN-LAST:event_jpanelb4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanelb2;
    private javax.swing.JPanel jpanelb3;
    private javax.swing.JPanel jpanelb4;
    private javax.swing.JPanel panelinicio;
    private javax.swing.JPanel panelop;
    // End of variables declaration//GEN-END:variables
}
